name: flutter_pinelabs
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  cidroy_analysis: ^0.0.3
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cidroy.flutter_pinelabs
        pluginClass: FlutterPinelabsPlugin
